export const examples = [
    { name: 'Animation', path: 'animation.html' },
    { name: 'Annotations', path: 'annotations.html' },
    { name: 'AR Avatar', path: 'ar-avatar.html' },
    { name: 'Basic Shapes', path: 'basic-shapes.html' },
    { name: 'Basic Particles', path: 'basic-particles.html' },
    { name: 'Car Configurator', path: 'car-configurator.html' },
    { name: 'First Person Teleport', path: 'first-person-teleport.html' },
    { name: 'FPS Controller', path: 'fps-controller.html' },
    { name: 'Game: Falling Blocks', path: 'vibe-falling-blocks.html' },
    { name: 'GLB Loader', path: 'glb.html' },
    { name: 'Physics', path: 'physics.html' },
    { name: 'Physics Cluster', path: 'physics-cluster.html' },
    { name: 'Positional Sound', path: 'positional-sound.html' },
    { name: 'Shoe Configurator', path: 'shoe-configurator.html' },
    { name: 'Solar System', path: 'solar-system.html' },
    { name: 'Sound', path: 'sound.html' },
    { name: 'Splat: Annotations', path: 'splat-annotations.html' },
    { name: 'Splat: Simple', path: 'splat-simple.html' },
    { name: 'Splat: Flipbook', path: 'splat-flipbook.html' },
    { name: 'Text Elements', path: 'text.html' },
    { name: 'Text 3D', path: 'text3d.html' },
    { name: 'Tweening', path: 'tween.html' },
    { name: 'Video Recorder', path: 'video-recorder.html' },
    { name: 'Video Texture', path: 'video-texture.html' }
];
